
#Spring secure
size:
  username: 4
  password: 4

#Server port

server:
  port: 8001
spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
  datasource:
    data: classpath:/import.sql
    url: jdbc:derby:memory;create=true
    username: app
    password: app
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyDialect

debug: false







